### ISSUE TITLE
Problems by checking out the project

### ISSUE THREAD

**Issue by enriquemorenotent** [SebLague/Marching-Cubes#1]
I just checked out the project, and I run into some problems:

First I had to convert the project from 2018.3.2f1to 2018.3.8f1

After this was done, I was greeted by the following error message:

> Compute Shader: The destination buffer in CopyComputeBufferCount is not of type Raw or IndirectArguments. DX11 only supports CopyComputeBufferCount to these types.

While trying to execute the scenes, or just looking around the scene, I got often this message:

> OutOfMemoryException: Out of memory
> MeshGenerator.UpdateChunkMesh (Chunk chunk) (at Assets/Scripts/MeshGenerator.cs:201)

And when inspecting the components in the scenes, I saw 2 components that had a "missing script" warning. The "Main Camera" in the submarine scene, and the "Chunk holder" in the terrain scene.

![image](https://user-images.githubusercontent.com/368842/57246400-703ef180-703d-11e9-8c98-bfedf38b1fcf.png)

![image](https://user-images.githubusercontent.com/368842/57246412-7c2ab380-703d-11e9-84fd-8d2750c76142.png)

What could this be hapenning?

**Comment by AquilaRapax** [comment]
I had the same out-of-memory and ComputeShader problem, and it turned out, that you have to provide a `ComputeBufferType`, when using DirectX. So in MeshGenerator.cs@290 just add `ComputeBufferType.Raw` as third parameter when creating `triBoundBuffer`
> triCountBuffer = new ComputeBuffer(1, sizeof(int), ComputeBufferType.Raw);

Unfortunately i cannot help with the missing scripts. I have them too, but it seems to run anyway.

**Comment by enriquemorenotent** [comment]
That solved everything! THanks!
